# Generated by Django 6.0.5 on 2026-05-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catt',
            new_name='Cat',
        ),
    ]
