# Generated by Django 6.0.5 on 2026-05-28 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_landlord_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Landlord',
            new_name='landlord',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cat')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
